version: '3.8'
services:
  app:
    image: laravelphp/php-fpm
    container_name: salon-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: salon-db
    restart: always
    environment:
      MYSQL_DATABASE: saloncrm
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
